remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Toymoa Blog
description: Welcome to my blog
baseurl: "/Blog"
url: "https://toymoa.github.io"

header_pages:
  - about.md